### ISSUE TITLE
ESPN should allow espncdn.com

### ISSUE THREAD

**Issue by bbondy** [brave/adblock-lists#1]
CC @jonathansampson in case you want to take this. You can ping me for help on how to do that. 

Migrated from Serg's bug here:
https://github.com/bbondy/abp-filter-parser-cpp/issues/41

We block that huge resource, probably we should allow to load espncdn.com domain in espn.com:

http://a.espncdn.com/combiner/c?v=1.0.2&css=m/reset.css,m/fonts.css,m/base.css,m/layout/body.css,m/layout/navigation.css,m/layout/footer.css,m/layout/hidepageshell.css,m/modules/forms.css,m/modules/filters.css,m/modules/tables.css,m/modules/images.css,m/modules/icons.css,m/modules/media.css,m/modules/legacy.css,m/modules/overlays.css,m/modules/expander.css,m/modules/module.css,m/modules/subsection.css,m/modules/pagination.css,m/modules/ads.css,m/modules/ads.popup.css,m/modules/sponsored.css,m/modules/myespnPanel.css,m/modules/inline-nav.css,m/modules/zebra-links.css,m/modules/mem.css,m/modules/handset-button-controls.css,m/modules/p13n.css,m/modules/featured-columnist.css,m/modules/date-picker.css,m/modules/photogallery.css,m/modules/playersform.css,m/modules/poll.css,m/modules/rankings.css,m/modules/scoreboard-carousel.css,m/modules/sportsnation.css,m/modules/paginatedModule.css,m/modules/standings.css,m/modules/stats-table.css,m/modules/story.css,m/modules/storypage.css,m/modules/insider.css,m/modules/video.css,m/modules/watchespn.css,m/modules/btn-toggle-tablet.css,m/modules/add2home.r2.css,m/modules/foresee.css,m/modules/tabs.css,m/modules/share.css,m/modules/facts.css,m/modules/bites.css,m/modules/weekendwatch.css,m/modules/pickcenter.css,m/themes/sports.css,m/themes/games.css,m/themes/local.css,m/sprite.css,m/layout/device.css,m/page/deportes/redirect.css,m/modules/conversations.css,m/modules/accordion.css,m/page/video/videoPlayer.css,m/modules/nflnation.css,m/modules/teams.r9.css,m/page/embed/embed.css,m/modules/freshmanfocus.css,m/modules/tidbits_module.css,m/modules/d_image_module.css,m/page/jquery.smartbanner.css

**Comment by ryanbr** [comment]
We have this in Easylist:

`@@||espncdn.com/combiner/$stylesheet`

Safe to close this issue report @bbondy ?

**Comment by bbondy** [comment]
sounds good
