### ISSUE TITLE
Outlook.com Ads not being Blocked even with Brave Shields set to "Aggressive Mode"

### ISSUE THREAD

**Issue by DesertBear** [brave/adblock-lists#1081]
**Description:**
Ads are not being blocked on outlook.com, even with Brave Shields set to "Aggressive Mode".  

They are also not blocked when "Fanboy Annoyances List" and "uBlock Annoyances List" are enabled as well.

**Steps to Reproduce:**
**1)** Go to `brave://settings/shields` and set "Trackers & ads blocking" to "Aggressive".

**2)** Go to `brave://settings/shields/filters` and enable "Fanboy Annoyances List" and "uBlock Annoyances List".

**3)** Sign in to https://outlook.live.com/mail/0/

**4)** Observe the top of the inbox.

**Actual result:**
Ads are not being blocked.

_Screenshot showing ads visible with Brave Shields enabled:_
![Screenshot A](https://user-images.githubusercontent.com/27423064/219976323-a51adb87-f23b-4188-9cf5-d9db00350069.jpg)

**Expected result:**
The Ads should be blocked.

_Screenshot showing ads correctly blocked with uBlock Origin using default settings:_
![Screenshot B](https://user-images.githubusercontent.com/27423064/219976332-b51268dc-4b82-41c0-9c27-1abf12f4422f.jpg)

**Brave version (brave://version info):**
```
Brave:     1.48.167 Chromium: 110.0.5481.104 (Official Build) (64-bit) 
Revision:  46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS:        Windows 10 Version 22H2 (Build 19045.2604)
```

**Comment by ryanbr** [comment]
Can you check the latest Brave Nightly (Version 1.50.56) that this is fixed @DesertBear

**Comment by antonok-edm** [comment]
(as per https://github.com/brave/brave-browser/issues/28609)

**Comment by DesertBear** [comment]
The issue appears to be resolved in the below nightly build.  Thanks.

_Version 1.50.58 Chromium: 110.0.5481.104 (Official Build) nightly (64-bit)_

![Screenshot Nightly](https://user-images.githubusercontent.com/27423064/220941904-c0981a2f-1003-474a-88bf-eeadf3b4f87b.jpg)
