### ISSUE TITLE
Startpage.com Ads not being Blocked even with Brave Shields set to "Aggressive Mode"

### ISSUE THREAD

**Issue by DesertBear** [brave/adblock-lists#1082]
**Description:**
Ads are not being blocked on startpage.com, even with Brave Shields set to "Aggressive Mode".  

They are also not blocked when "Fanboy Annoyances List" and "uBlock Annoyances List" are enabled as well.

**Steps to Reproduce:**
**1)** Go to `brave://settings/shields` and set "Trackers & ads blocking" to "Aggressive".

**2)** Go to `brave://settings/shields/filters` and enable "Fanboy Annoyances List" and "uBlock Annoyances List".

**3)** Go to startpage.com and search for "[Sites can ask to use fonts installed on your device](https://www.startpage.com/do/search?q=%22Sites+can+ask+to+use+fonts+installed+on+your+device%22&segment=startpage.brave)"

**4)** Observe the bottom of the search results and also the right-hand side.

**Actual result:**
Ads are not being blocked.

_Screenshot showing ads visible with Brave Shields enabled:_
![Screenshot A](https://user-images.githubusercontent.com/27423064/219978000-4257646d-2360-449a-9cf4-9e8f2120af00.jpg)

_Screenshot showing Brave Shields element picker, which seems to be linking both the ad at the bottom of the search results and also the section on the right-hand side:_
![Screenshot B](https://user-images.githubusercontent.com/27423064/219978004-3b300757-181c-4539-bf66-55748c3acb10.jpg)

**Expected result:**
The Ads should be blocked.

_Screenshot showing ads correctly blocked with uBlock Origin using default settings:_
![Screenshot C](https://user-images.githubusercontent.com/27423064/219978008-f0270c7e-3a7c-406a-95c8-a580eefe466f.jpg)

**Brave version (brave://version info):**
```
Brave:     1.48.167 Chromium: 110.0.5481.104 (Official Build) (64-bit) 
Revision:  46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS:        Windows 10 Version 22H2 (Build 19045.2604)
```

**Comment by pes10k** [comment]
Thanks for filing this issue @DesertBear ! We'll take a look and get it sorted!

@antonok-edm @ryanbr could you guys take a look?

**Comment by antonok-edm** [comment]
We've addressed the issue in our filter lists; ads should be hidden on Startpage in Aggressive mode as of `Brave Ad Block Updater - Version: 1.0.207` in `brave://components` (should be available on all channels within the next 24 hours).

As for the issue of the element picker showing up in multiple locations on the page, we'll track it in https://github.com/brave/brave-browser/issues/28423 as it's likely related.

Thanks for the report @DesertBear!
