### ISSUE TITLE
Are pull requests accepted on this repo?

### ISSUE THREAD

**Issue by hiteshsharma** [brave/adblock-lists#1094]
I'm trying to get one of LinkedIn's domains (lnkd.in) added to the [social domain list](https://raw.githubusercontent.com/brave/adblock-lists/master/brave-lists/brave-social.txt) for allowing content loaded from licdn.com (LinkedIn's cdn) as described in https://community.brave.com/t/website-broken-because-assets-getting-blocked/473280/4

I can make the change here and submit a PR but not sure if PRs are accepted in this repo from non-contributors of this repo. Please share the process for getting the list updated. Thanks!

**Comment by pes10k** [comment]
Hi @hiteshsharma , yes pull requests are welcome, thank you for taking the time to create an issue too.  @ryanbr and @antonok-edm would be best suited to decide whether this is a good change for Brave users

**Comment by pes10k** [comment]
I should have assumed :)

**Comment by hiteshsharma** [comment]
Thanks for the quick change. What is brave browser's release timeline?

**Comment by ryanbr** [comment]
Should be resolved, can you confirm @hiteshsharma

**Comment by hiteshsharma** [comment]
@ryanbr yes it is resolved. Thanks for the quick turnaround
