### ISSUE TITLE
stirileprotv.ro

### ISSUE THREAD

**Issue by ghost** [brave/adblock-lists#1146]
anti-adblock on `https://stirileprotv.ro/protvnews/`

![Screenshot from 2024-03-08 16-04-00](https://github.com/brave/adblock-lists/assets/167821/333b4121-0b12-483e-bcc0-cf4a3f2090f4)

placeholder on `https://stirileprotv.ro/`

![Screenshot from 2024-03-08 16-04-51](https://github.com/brave/adblock-lists/assets/167821/5c412708-5028-4835-ba07-7129367cd861)

does Brave not support `redirect-rule`? if not, why?

**Comment by ryanbr** [comment]
Enable Romian List, working here now.
