### ISSUE TITLE
Add Title and Expires field to Brave lists.

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/adblock-lists#1231]
Brave finally supports the `Expires` property in lists, it would be good if Brave added `Expires:` property and also the `Title` one to the Brave lists, so people adding them the Default lists as custom lists either for testing purposes (like mentioned here https://github.com/brave/brave-browser/issues/29321) or people building Brave from source (https://github.com/brave/brave-browser/issues/26143#issuecomment-1341936225), can have the lists updated more frequently.

But also prettify the Brave lists as Custom so it doesn't look like this:

![image](https://github.com/brave/adblock-lists/assets/122518587/4700462f-720d-4169-a172-4397bb712a5a)

**Comment by pes10k** [comment]
cc @antonok-edm , since i think some of this is either already planned

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
@pes10k
If you are talking about the implementation itself, `Expires:` was implemented last week https://github.com/brave/brave-core/pull/18836 and `Title:` in February this year https://github.com/brave/brave-core/pull/17125

So Brave lists only need, for example: 

```
! Title: Brave Unbreak
! Expires: 1 day
```
Also, Brave already have titles for the Brave lists in the [default.json](https://github.com/brave/adblock-resources/blob/master/filter_lists/default.json), so I guess, it's only about copying and pasting them.

Seems like something 'quick n easy', since this will not affect anything about the lists, only the way they look when added as custom and how frequently they automatically update; and then just pushing the update button in the list should reflect these changes immediately.

The thing is mostly how only Brave Team knows how frequent the lists should be updated when added as custom, to avoid problems like high traffic in servers like github that don't belong to Brave, like happened/was reported in October 2022 https://adguard.com/en/blog/easylist-filter-problem-help.html

**Comment by pes10k** [comment]
Understood.  I can only say that, nothing UI related is ever actually "quick n easy" in a code base as big as chromium, and from a position like Brave's (where we need to make sure the modifications we make are as painless-as-possible to apply across chromium versions). As always, PRs welcome ;)

More seriously, like i said, the change you're describing something we're interested in doing.  I dont have a timeline for you though. @antonok-edm may choose to add more information if he has any.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
no no @pes10k the change is in the top part of these Brave lists:
[brave-unbreak.txt](https://raw.githubusercontent.com/brave/adblock-lists/master/brave-unbreak.txt), [brave-specific.txt](https://raw.githubusercontent.com/brave/adblock-lists/master/brave-lists/brave-specific.txt), [brave-social.txt](https://raw.githubusercontent.com/brave/adblock-lists/master/brave-lists/brave-social.txt), [brave-android-specific.txt](https://raw.githubusercontent.com/brave/adblock-lists/master/brave-lists/brave-android-specific.txt), [brave-sugarcoat.txt](https://raw.githubusercontent.com/brave/adblock-lists/master/brave-lists/brave-sugarcoat.txt).

For example, like the uBlock filter list: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt where you can see:

```
! Title: uBlock₀ filters
! Description: Filters optimized for uBlock, to be used along EasyList
! Expires: 5 days
! Last modified: %timestamp%
! Homepage: https://github.com/uBlockOrigin/uAssets
! License: https://github.com/uBlockOrigin/uAssets/blob/master/LICENSE
!
! GitHub issues: https://github.com/uBlockOrigin/uAssets/issues
! GitHub pull requests: https://github.com/uBlockOrigin/uAssets/pulls
```
And brave will read those lines and then set the local state file as:

![image](https://github.com/brave/adblock-lists/assets/122518587/d9e9d7a1-e1fd-4038-aa3e-78d08a25311f)

And then show the title in the custom lists automatically:
![image](https://github.com/brave/adblock-lists/assets/122518587/3cc10a11-0248-4dd7-bbc3-21afb93d58d3)

Everything is there, and I would make a PR, but I think only @ryanbr knows exactly, since he works with Brave lists (and Easylist and Fanboy lists), how frequent Brave lists should be updated, if he thinks 3 days is fine for the unbreak (which is the one that gets updated more often), then `! Expires: 3 days` if he thinks 7 days, then `! Expires: 7 days` should be added to it, even if by default Brave updates the lists every 7 days, just to make sure Brave will not cause some awkward high traffic in servers like github, like happened in Easylist servers in October.
The problem is, If it was for me, I wouldn't even wait 1 day to update Brave unbreak, but I know that might not be necessary, and I don't update Brave lists to know how frequent the changes should be expected.
