### ISSUE TITLE
Please add help in the README file to use these lists for PiHole as well

### ISSUE THREAD

**Issue by mimranfaruqi** [brave/adblock-lists#1476]
Hi,

Adding help for PiHole will actually help me and others to block youtube and other ads across my network. Perhaps Brave extensive list and normal list so that anyone can switch between the lists using PiHole.

**Comment by iam-py-test** [comment]
Disclaimer: I have no affiliation with Brave. My statements are mine and mine alone, and Brave is not responsible for any errors
>  block youtube [...] ads across my network

PiHole can not block YouTube ads; you need something like Brave browser, or alternatively a browser extension such as uBlock Origin or AdGuard
> Perhaps Brave extensive list and normal list so that anyone can switch between the lists using PiHole.

Most of the filters in the Brave lists can not work in PiHole, i.e. "cosmetic" filters which hide parts of websites, scriptlets which modify how websites work, etc.
Thank you
