### ISSUE TITLE
Adblock detected YouTube Indonesia server

### ISSUE THREAD

**Issue by Jokopentil** [brave/adblock-lists#1601]
![Screenshot_2024-03-19-20-35-35-14_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/brave/adblock-lists/assets/114223791/61d95b77-c0bb-48e0-abf2-26df14cb345a)

![Screenshot_2024-03-19-20-35-12-68_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/brave/adblock-lists/assets/114223791/e00ae25f-1df4-45c0-a2a1-ebfc03e1aefe)

Cannot play YouTube

**Comment by Jokopentil** [comment]
YouTube Android

**Comment by Jokopentil** [comment]
No

**Comment by ryanbr** [comment]
Thanks for confirming
