### ISSUE TITLE
Thewire.in ad leftovers

### ISSUE THREAD

**Issue by libreom** [brave/adblock-lists#1712]
Remove the ad leftovers spaces so it can be more efficient example-
https://m.thewire.in/article/politics/notes-from-up-understanding-the-significance-of-rae-bareli-and-amethi
![Screenshot_20240504-122554_Brave](https://github.com/brave/adblock-lists/assets/111110599/2f699c9e-418f-4044-abc9-9ab60ef6fad2)
Id start with `ATD`
Add to normal list not any specific list, so all people benefit

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b104d566ede7bbcfaa7e633edf8910ad4cae8ec0

**Comment by ryanbr** [comment]
Filter rules be updated in the next 3-4 hrs.
