### ISSUE TITLE
Broken Site - gazeta.ru

### ISSUE THREAD

**Issue by Cybo1927** [brave/adblock-lists#190]
When Brave's shields are enabled the site (gazeta.ru) breaks completely

**Comment by ryanbr** [comment]
This should fix it. 

https://github.com/brave/adblock-lists/pull/205

(Update in the next 24-48hrs), if wish to confirm.

**Comment by Cybo1927** [comment]
Sorry for not knowing how to edit video but I just updated my browser and the site still breaks.

youtube.com/watch?v=N31retKFjD4

**Comment by ryanbr** [comment]
Can you confirm everything is working @Cybo1927 ?
