### ISSUE TITLE
Many ads (pop-up tabs).

### ISSUE THREAD

**Issue by HeyPrinceInd** [brave/adblock-lists#1968]
many new tabs opening after clicking anywhere.

Fix for this website: https://vegamovies.nu/

**Comment by antonok-edm** [comment]
I was able to click on a bunch of links without any new tabs opening; I think this is fixed? If not, please reopen with more detail and we can take another look.

**Comment by HeyPrinceInd** [comment]
Yes. There is still too many ads (opening new tab).

fix this site too : https://movies4u.casa
