### ISSUE TITLE
Unusable site *.taobao.com

### ISSUE THREAD

**Issue by fhoshino** [brave/adblock-lists#308]
Is there a way to add an exclusion for *.taobao.com and alicdn within browsing in taobao.com?
Due to each shop and function has it's own subdomain and cross referencing the main site's cookies, this makes controlling shield up & down hectic to use the site.

**Comment by snyderp** [comment]
I think its fine to add these exceptions if we can identify which ones are tracking related, which perform some other function, and which are unknown. There is a lot of explicitly privacy harming stuff on those domains (especially alicdn) and so blanket domain exceptions would be way too broad.  

Maybe there is an existing CN or similar filter list we could pull more narrow exception rules from?

**Comment by ryanbr** [comment]
Hey @fhoshino I see we're blocking a script from `alicdn.com` creating a false positive on the site.

https://github.com/easylist/easylist/commit/92c8a10e1db0bc14e28ce426a1a51a8df8db6e52

Give it 24-48hrs, let me know if it helps. Also noticed some fingerprinting on the site in Shields, which affect the site functionality.

**Comment by ryanbr** [comment]
Closing, this has been resolved.
