### ISSUE TITLE
hydrax anti-adblock message

### ISSUE THREAD

**Issue by zmni** [brave/adblock-lists#327]
Example site: `https://9anime.ru/watch/spirited-away.w48o/9pw53q` and change source server to hydrax.

Related issue: https://github.com/uBlockOrigin/uAssets/issues/6851.

Thank you.

**Comment by ryanbr** [comment]
Should be resolved, 

https://github.com/easylist/easylist/commit/b801896c6ebd1d2270174f451025075948f203f0

Further improvements will be occuring in Brave Nightly also.
