### ISSUE TITLE
Prebake List Replacement

### ISSUE THREAD

**Issue by mpaunovic** [brave/adblock-lists#334]
It looks like the "Prebake" list was abandoned a while back and therefore it's obsolete. Please consider replacing it in brave://adblock with the "I don't care about cookies" list.

https://www.i-dont-care-about-cookies.eu/

https://www.i-dont-care-about-cookies.eu/abp/

Thank you.

**Comment by krystian3w** [comment]
Or `EasyList cookies`

**Comment by krystian3w** [comment]
https://github.com/brave/ad-block/blob/master/lists/regions.h

**Comment by ryanbr** [comment]
Related: https://github.com/brave/adblock-rust/pull/67

**Comment by pes10k** [comment]
@ryanbr can this be closed now bc of https://github.com/brave/adblock-rust/pull/67 ?

**Comment by ryanbr** [comment]
Yeah, closing.
