### ISSUE TITLE
Replace regional filter list for Japanese

### ISSUE THREAD

**Issue by Yuki2718** [brave/adblock-lists#355]
Having seen issue reports have been ignored by the maintainer of ABP Japanese filter, I decided to propose this. Actually the filter is what no sensible Japanese user of adblocker uses. It's almost dead, causes problems even for Japanese sites, doesn't block newer ads, and its maintainer has too rigid support policy which doesn't work well with Brave. Here `https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-438127834` was some of related discussion in English. There are better alternatives but as the choice for default is such a big decision I'll just comment on the most popular candidates as objectively as possible (still can't eliminate my subjective opinion).

- AdGuard Japanese
`https://kb.adguard.com/en/general/adguard-ad-filters#japanese`
well-maintained as you expect, the default filter for Japanese on uBlock Origin. A big plus is this filter is very compatible with EasyList/EasyPrivacy (other candidates have some overlap). A potential problem may be apparently not many Japanese adblock user use this and thus reports are often from foreigners, which resulted in some biases in its coverage, i.e. compared to other candidates, more rules for otaku related sites, roundup blogs, and adult sites while less rules for websites that "average" Japanese internet user will frequently visit.

- Tofu filter
`https://github.com/tofukko/filter/blob/master/Adblock_Plus_list.txt`
probably the most popular list among Japanese adblock user for PC. Now it is shared on Github (it was not when uBO switched their default filter for Japanese) so I guess it will be possible to report issues there, tho so far no issue was made (Japanese users have been reporting issues on a blog by the maintainer). While it's effective, its generic cosmetic filters tend to be aggressive and occasionally cause false positives - not sure if applying them only for third-party mitigates this or not.

- 280blocker for japanese mobile site
`https://280blocker.net/download/`
the most popular list for mobile, but can also be used for PC and it seems actually some people, including the maintainer himself, are doing so. It has been most actively developed (1-3+ updates per month for years), and unlike other candidates it uses standard ABP syntax only. The ABP format list blocks some social staff and annoyances too. Reporting issue is usually done by a dedicated form on their homepage. The biggest problem will be it's under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/).

- Mochi filter
`https://github.com/eEIi0A5L/adblock_filter/blob/master/mochi_filter.txt`
another popular list for PC, and the maintainer offers a list for mobile named Tamago filter (`https://github.com/eEIi0A5L/adblock_filter/blob/master/tamago_filter.txt`) too. This filter is least likely to cause false positives as few generic rules are used, tho at the same time the coverage of blocking may be limited. The maintainer is very responsive and seems to have no trouble to communicate in English. He declared he doesn't hold any rights on all of his filters, meaning they are under [CC0](https://creativecommons.org/share-your-work/public-domain/cc0) (if you have doubt, ask him).

**Comment by ryanbr** [comment]
Thanks, will look at the options for a Japanese replacement. If I were to side on a replacement, the Adguard filter looks decent.

**Comment by Yuki2718** [comment]
My bad, but I found it's essentially duplicate of https://github.com/brave/adblock-rust/issues/66. The issue on this repo should be limited to sth about in-house filters, shouldn't it?

**Comment by ryanbr** [comment]
Looking at this further. 

- `280blocker` is only effective if you use all 3 lists (or use 2/3 lists).  There isn't a combined filter

- `Tofu filter`, and `Mochi` unnecessary English filters, and not just strictly Japanese filters.

- Adguard seems to be the most sane, apart from the Adguard specific code, seems decent. Also uBO has Adguard Japanese as the default Japanese list.

**Comment by ryanbr** [comment]
Another option we include 2 Japanese lists `280blocker domains` and `Adguard`

**Comment by Yuki2718** [comment]
> 
> 
>     * `280blocker` is only effective if you use all 3 lists (or use 2/3 lists).  There isn't a combined filter

The ABP format file alone is all needed, the domain list (ABP format) is extracted from this list for domain-level blocking and others are irrelevant to Brave. However, the ABP format file blocks some social staff and annoyances so not a pure ad-block list.

>     * `Tofu filter`, and `Mochi` unnecessary English filters, and not just strictly Japanese filters.

Yes, as I noted there are some overlap.

>     apart from the Adguard specific code, 

I hope in future Brave convert them to compatible syntax. 

> 
> Another option we include 2 Japanese lists `280blocker domains` and `Adguard`

I guess this will be quite reasonable and effective, although there are some duplicates.

**Comment by Yuki2718** [comment]
Can I close this issue now?

**Comment by ryanbr** [comment]
Yeah, ticket has been resolved. Closing
