### ISSUE TITLE
Add AdGuard Mobile ads filter and enable it by default on mobile

### ISSUE THREAD

**Issue by Yuki2718** [brave/adblock-lists#391]
While EasyList and regional lists block ads on mobile sites too, majority of reports to them are for PC sites. This reflects a fact that these PC ad-blocker are not as widely used or as powerful on mobile as PC. AG dominates ad-blocking on mobile devices and their Mobile filter is enabled by default on uBO running on Firefox Android. Adding to that, now AG Japanese replaced ABP Japanese, but at AdguardFilters mobile-only issues on Japanese sites are addressed in Mobile filter and not in Japanese filter. So without Mobile filter you need to address these mobile-only issues in Brave Unbreak which will be waste of work.

**Comment by ryanbr** [comment]
This would create many duplicate filters, any specific mobile english filters can be added to Easylist. It would slow things down given the memory/cpu requirements of mobile devices

Maybe the only option would to add `brave://adblock`. ?

**Comment by Yuki2718** [comment]
I don't think there will be too many duplicates since Mobile filter is used alongside with Base filter which is derived from EasyList, however, for that matter they provide optimized version, e.g. https://filters.adtidy.org/ios/filters/11_optimized.txt
On uBO it has only 1,508 network filters and 3,399 cosmetic filters. Another option may be taking their whitelist part only (directly from their Github) so that you don't need to fix mobile-only issues on Japanese sites which are already addressed by Mobile filers.

> 
> Maybe the only option would to add `brave://adblock`. ?

Does that mean it will be optional which user explicitly enable?

**Comment by ryanbr** [comment]
Adguard regional Japanese is a stand-alone, that can work with Easylist.  We don't need to adopt all the Adguard filters because of it. We've been adding mobile filters (cosmetic, adservers etc) to Easylist, adding Adguard Mobile would be a redundant. The benefit is minimal to add another generic list, and the higher changes of false positives. 

If there are missing ads, or elements (Desktop or Mobile). Can be requested https://forums.lanik.us/viewforum.php?f=62  It'll be added like any other filter.

It's a No from me.

**Comment by Yuki2718** [comment]
@ryanbr Okay, I'll respect your opinion. Closed.

**Comment by hirorpt** [comment]
> Maybe the only option would to add brave://adblock. ?

As @Yuki2718 mentioned, AdGuard Mobile also work as regional filters. Therefore, it should be offered as an optional filter at least. 

Off-topic: I'm finding EL/EP derived false positives every day, but I haven't seen any false positives from AdGuard Mobile yet. @ryanbr, You'd be better off watching out for risky filters you added than being wary of imaginary false positives in third-party filters.

**Comment by ryanbr** [comment]
@hirorpt EP is far more wide ranging than Adguard (considered the many international regions it covers), false positives are addressed as they occur.

**Comment by Yuki2718** [comment]
Three years past and many things changed, I guess it's good time to revisit.
>  any specific mobile english filters can be added to Easylist.

The point is that we at AdGuard address every mobile sites issues of all region. I don't think anyone can continuously import these reginal fixes to EL or Brave as the list is very actively developed. I admit there will be some overlap, despite I cleared out *a lot* of them ([e.g.](https://github.com/AdguardTeam/AdguardFilters/commit/7d6e9edc8385d6d55411ffeae7a3088f07c460a7)); however, Brave now adopted token-based approach which makes having redundant filters much less problematic. [Brave's own article] demonstrated adding 16,000 filters doesn't add 1 μs difference in processing a request. Given all these, I believe overall benefit of mobile sites issues fixed (remember, they include many of scriptlet and CSS rules) is more important than having duplicates.
