### ISSUE TITLE
Pull useful rules from final brave-disconnect.txt file into brave-unblock.txt

### ISSUE THREAD

**Issue by pes10k** [brave/adblock-lists#413]
Since we'll no longer be using brave-disconnect.txt as of https://github.com/brave/adblock-rust/issues/113, we should make sure to pull any needed rules from there into brave-unblock.txt (or even better, upstream to Easy{List,Privacy})

**Comment by ryanbr** [comment]
No filters needed from brave-disconnect.txt (or disconnect list in general). The only major differences not included by EL/EP was outbrain[1] which was included in:  Now we have Peter Lowes list, Our block on Outbrain isnt now needed either..

1. `||outbrain.com^$third-party,domain=~sphere.com`

Safe to close this @pes10k @antonok-edm

**Comment by pes10k** [comment]
Yep, looks good to close to me.  Thanks @ryanbr !

**Comment by ryanbr** [comment]
Resolved, closing. We're looking good.
