### ISSUE TITLE
Correct a filter name in brave://adblock/

### ISSUE THREAD

**Issue by Yuki2718** [brave/adblock-lists#425]
The Japanese filter was replaced from ABP-JP to AG-JPN by https://github.com/brave/adblock-lists/issues/355 but I found the name in brave://adblock/ has not changed:

![brave](https://user-images.githubusercontent.com/58900598/88525260-566c3e80-d035-11ea-8004-37c15c10f1c2.png)

Confirmed both on Windows (Brave 1.11.101) and Android (1.10.99; chrome://adblock) version.

**Comment by antonok-edm** [comment]
This is actually an issue from https://github.com/brave/brave-core, the list of regional options is effectively hard-coded into the browser and has to "catch up" using the browser's release cycle.

However, as of https://github.com/brave/brave-core/pull/6125 (which is currently in Brave Nightly), we've started loading these lists dynamically, so this should no longer be an issue going forwards.

**Comment by Yuki2718** [comment]
Apparently this was fixed in stable too, closing.
