### ISSUE TITLE
Anti-adblock

### ISSUE THREAD

**Issue by ghost** [brave/adblock-lists#436]
**Below websites have Anti-adblock when Brave Shields are enabled:**

* `https://justlightnovels.com/`
* `https://jnovels.com/light-novels-epub/`

Brave browser Shields --> Aggressive  

Brave browser version (desktop) --> 1.11.104

**Comment by pes10k** [comment]
Thanks @Bluedot449 !

@ryanbr are these actionable / anything we can do about them, either in brave directly, or upstream?

**Comment by ryanbr** [comment]
Hey thanks for the report, have investigated.

 `https://justlightnovels.com` will be fixed in the next Brave release (due this week) when $generichide support is rolled out.

and `https://jnovels.com/light-novels-epub/`  https://github.com/uBlockOrigin/uAssets/pull/7752

**Comment by ryanbr** [comment]
Re-checked this, looking good. @ghost  If you see any other issues, just report it.
