### ISSUE TITLE
Include Fanboy Social, Annoyances and Enhanced Trackers List

### ISSUE THREAD

**Issue by ryanbr** [brave/adblock-lists#438]
Making these 3 lists available, in sync with the offerings with uBO. All 3 available in uBO.

> Social List: https://easylist-downloads.adblockplus.org/fanboy-social.txt

Will Hide Social (buttons, widgets etc) elements on a page

> Annoyances List: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt

Includes Social List, but also hides additional elements, New letter overlays, Cookie messages, self-promo banners.

> Enhanced Trackers: https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/enhancedstats-addon.txt

Test-bed for trackers, problematic trackers / some paywall trackers

**Comment by ryanbr** [comment]
Happy to start work on this week @pes10k  if this okay.

**Comment by pes10k** [comment]
@ryanbr these would be additional optional / "regional" lists?

**Comment by ryanbr** [comment]
Yeah, will be in additional/optional in `brave://adblock` @pes10k

**Comment by pes10k** [comment]
i think that sounds great @ryanbr , though lets wait until https://github.com/brave/brave-browser/issues/8838 lands, since that'll make that UI more friendly in general, and the whole regional / additional list infrastructure may change slightly in the meantime

**Comment by ryanbr** [comment]
https://community.brave.com/t/block-social-media-icons/153389/5   requested social items to be blocked

**Comment by Furax-31** [comment]
Are Fanboyz lists going to be added soon?

**Comment by ryanbr** [comment]
Closing, now resolved.
