### ISSUE TITLE
Blocked webfonts (thetimes.co.uk)

### ISSUE THREAD

**Issue by ShintoPlasm** [brave/adblock-lists#445]
Hello,

With adblocking turned on (both Standard and Aggressive), several webfonts are blocked - which leads to an incorrectly formatted comment section below articles.

**URL:** https://www.thetimes.co.uk (Paywall)

**Blocked content which should be whitelisted:**
https://publisher-assets.spot.im/times-of-london/tol-fonts/TimesDigitalRegular.woff2
https://publisher-assets.spot.im/times-of-london/tol-fonts/GillSansW01Medium.woff2
https://publisher-assets.spot.im/times-of-london/tol-fonts/TimesModern-Bold.woff

Thank you!

**Comment by ryanbr** [comment]
Hey @ShintoPlasm 

Have checked the site, nothing being blocked in the default lists. Which lists in `brave://adblock`  are enabled?

**Comment by ShintoPlasm** [comment]
Hello @ryanbr

No extra lists are selected. Even so, those three blocked webfonts are listed in the Shields view of cross-site trackers blocked.

**Comment by ryanbr** [comment]
Ah I see, Peter Lowes list is causing it.

`127.0.0.1 publisher-assets.spot.im`

**Comment by ShintoPlasm** [comment]
Right... The Peter Lowes list often causes breakages for me and I always disable it in uBO. I wasn’t even aware it was included in the standard Brave setup.

**Comment by ryanbr** [comment]
Reaching out, if not removed from List, we'll just submit a PR to uBO to benefit both projects.

**Comment by pgl** [comment]
`publisher-assets.spot.im` removed from my list. Feel free to ping me (@pgl) with other potential issues.

**Comment by ryanbr** [comment]
Has been removed, give it 24-48hrs @ShintoPlasm  for the list update

**Comment by ryanbr** [comment]
Safe to close now, since filter is removed. If not resolved after 3 days. tag me @ShintoPlasm

**Comment by ShintoPlasm** [comment]
Brilliant, thanks both!
