### ISSUE TITLE
Unblocked ad on https://ouo.press/

### ISSUE THREAD

**Issue by ghost** [brave/adblock-lists#448]
## Steps to reproduce:

 1. Go to: `https://ouo.press/L5h46A`
 2. Click on 'I'm human'.
 3. See the ad below the 'Get link' button
 
This particular image is very annoying and if somehow this can be hidden then I'd be really great for me.

Brave browser on Android: Version 1.12.113

![Screenshot_20200814_114423](https://user-images.githubusercontent.com/69662619/90219377-8bdd9e00-de23-11ea-90fe-010bb801c0b3.jpg)

**Comment by ryanbr** [comment]
Is this still applicable @ghost ? I'm unable to see this advert.

**Comment by ryanbr** [comment]
Closing, site still seems fine. Report here if you're still having issues.
