### ISSUE TITLE
Please, disable this for these sites.

### ISSUE THREAD

**Issue by Ramys** [brave/adblock-lists#498]
This sites.
```
https://g1.globo.com/
https://www.uol.com.br/
https://globoesporte.globo.com

```
The message reads as "You are seeing this message because ad or script blocking software is interfering with this page. Disable any ad or script blocking software, then reload this page."

For Android .

Thks.

**Comment by ryanbr** [comment]
@Ramys  does it occur on Brave desktop?

**Comment by Ramys** [comment]
On the desktop is working properly, it happens in the brave for Android..
@ryanbr

**Comment by ryanbr** [comment]
Okay, i'll look into it. See if there is any fixes we can do. It'll affect many google funding sites @Ramys

**Comment by Ramys** [comment]
all right, if i find anything else i will report.

**Comment by ryanbr** [comment]
Okay, lets see how this goes @Ramys give it 24-48hrs for the update to roll out.

**Comment by Ramys** [comment]
This update worked perfectly.
Thks..
