### ISSUE TITLE
ADBlock Detected - www.livehindusthan.com

### ISSUE THREAD

**Issue by Lucifer879** [brave/adblock-lists#547]
**URL(s) where the issue occurs**
`https://www.livehindustan.com`

**Describe the issue**
Getting AdBlock detected popup when trying to read a post/news even after setting shield to Block All Ads & Fingerprinting blocking - strict.

**Screenshot(s)**
![LiveHindusthan 1](https://user-images.githubusercontent.com/48880976/105196903-1c05d900-5b62-11eb-850e-82a02448539a.PNG)

**Versions**
Browser/version: Brave | 1.19.86 Chromium: 88.0.4324.96

**How To Reproduce**
Visit www.livehindustan.com and open any news/post, once landed slowly scroll towards the end. It will automatically pop up after 3 seconds.

**Comment by ryanbr** [comment]
@Lucifer879  landed a patch to fix this, give it 24-48hrs and we'll retest this

**Comment by ryanbr** [comment]
Looking good now @Lucifer879  ?

**Comment by ryanbr** [comment]
Re-checked this, looking good, closing ticket.
