### ISSUE TITLE
Cosmetic issue - placeholders of blocked ads aren't removed

### ISSUE THREAD

**Issue by Lucifer879** [brave/adblock-lists#552]
**URL(s) where the issue occurs**
`https://www.aajtak.in`, `https://www.bhaskar.com`, `https://www.news18.com/`

**Describe the issue**
As title says. All the ads are being blocked on these sites but placeholders of ads are getting slipped away because of that we have empty spaces.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/48880976/105482189-0ca39e80-5cce-11eb-87e3-a683dbc7b550.png)
![image](https://user-images.githubusercontent.com/48880976/105482303-3230a800-5cce-11eb-8b84-770d3727a22b.png)
![image](https://user-images.githubusercontent.com/48880976/105482448-63a97380-5cce-11eb-90cd-f16ea74342fc.png)
![image](https://user-images.githubusercontent.com/48880976/105482529-7fad1500-5cce-11eb-8984-897e4caa72c8.png)
![image](https://user-images.githubusercontent.com/48880976/105482742-d4509000-5cce-11eb-8fc8-1d83d3751dc7.png)

**Versions**
Browser/version: Brave | 1.19.86 Chromium: 88.0.4324.96

**How To Reproduce**
Set shield's Trackers & ads blocking to "Block ALL Ads" & Fingerprinting blocking to "Strict" Visit any listed site above, open any news/post, you will be able to see placeholders between paragraphs, below menu & above footer.

**Comment by ryanbr** [comment]
Okay landed the following

https://github.com/easylist/easylist/commit/421a4597662dfa5340de134de361fb81cf531970
https://github.com/easylist/easylist/commit/00c576c229b4373e5da5b3a9be482b5a6589c512


https://github.com/ryanbr/fanboy-adblock/commit/cfb20bb077af6d7ed9655b5926756fd0ebccd1a1
https://github.com/ryanbr/fanboy-adblock/commit/e30705c585ce8ee33256e83b21e03d5bd03b7b68
https://github.com/ryanbr/fanboy-adblock/commit/c176024144dbe31c6ffada5169e42d19fd3ed93b

Ensure you enable to `brave://adblock`, Fanboy India filters.

Give it 24-48hrs for the updates to go out.

**Comment by ryanbr** [comment]
Just checking  @Lucifer879   Has this been resolved?

**Comment by ryanbr** [comment]
Closing should be resolved
