### ISSUE TITLE
unbreak logmein

### ISSUE THREAD

**Issue by alazare619** [brave/adblock-lists#561]
- Examples - 
https://qwerthnjklasd.logmein.com/js/tracking.js
https://lkjsdflhkasdfjlogmein.com/js/tracking.js
https://sadfasdfhkga.logmein.com/js/tracking.js

The above file is always random domain /js/tracking. however that file is necessary for logmein to work so it equates out to having to always disable the blocker while trying to use logmein.

**Comment by ryanbr** [comment]
When does this show up @alazare619  ?  Just logged in too https://secure.logmein.com/central/Central.aspx

**Comment by alazare619** [comment]
it shows when you launch and get the login screen for the domain
