### ISSUE TITLE
Brave on iOS breaks QR-code on systembolaget.se

### ISSUE THREAD

**Issue by Dyras** [brave/adblock-lists#592]
Hello! It seems the Shield on Brave iOS breaks the QR codes on systembolaget.se (a Swedish liquor store).

Any chance you could fix it?

Example link: https://www.systembolaget.se/hamta-i-butik/E10428198/

Edit: Wrote Android instead of iOS. Old habit, I guess.

**Comment by ryanbr** [comment]
Sure, can take a look

**Comment by ryanbr** [comment]
No easy fix, but disabling fingerprinting helps here @Dyras

**Comment by Dyras** [comment]
@ryanbr ah, I was hoping there could be some fix to fix this for all users by default :|

**Comment by ryanbr** [comment]
Could you generate the QR code as an image?

**Comment by Dyras** [comment]
Working now!
