### ISSUE TITLE
gigazine.net dismissable GFC anti-adblock

### ISSUE THREAD

**Issue by Yuki2718** [brave/adblock-lists#595]
`https://gigazine.net/`

<details>
<summary>Screenshot</summary>

![gigazine](https://user-images.githubusercontent.com/58900598/116722622-983d7180-aa19-11eb-917c-63c3a804f6d8.png)

</details>

It doesn't occur on uBO ~~thx to generic GFC fix~~ so Brave Shield-specific issue (AdGuard added specific fix in their Annoyances list). I wonder if it can be fixed in either Brave Unbreak or Fanboy Annoyance - it looks not requiring extended syntax (scroll not locked).

**Comment by Yuki2718** [comment]
@pes10k 
Even better will be Brave to support the generic fix: `*##[class^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-height:1px!important)`

**Comment by ryanbr** [comment]
Will also be resolved when landing https://github.com/brave/adblock-resources/pull/28 @Yuki2718
