### ISSUE TITLE
www.gorin.jp: This page has been blocked by Brave

### ISSUE THREAD

**Issue by hirorpt** [brave/adblock-lists#614]
### URL where the issue occurs
`https://www.gorin.jp`

### Describe the issue
`gorin.jp`, the official video provider of the Tokyo Olympics, is completely unavailable. This is probably due to incompatibility between AdGuard Japanese and Brave.

### Screenshot
<details><summary>Screenshot:</summary>

![Screenshot](https://user-images.githubusercontent.com/82331005/126954583-e4a1fb64-f3d7-4812-a908-e0de8e8ad27b.png)
</details>

### Settings
Adguard Japanese filters (日本用フィルタ) is subscribed 

### Notes
~~~
! Temporal fix
||gorin.jp/tokyo-assets/static/entrance/gorin_tead_prd/$subdocument,badfilter
~~~

**Comment by ryanbr** [comment]
Cheers, will investigate @hirorpt

**Comment by Yuki2718** [comment]
I can't reproduce even with Brave's built-in blocker (added a slightly modified rule to circumvent $badfilter, Shield icon shows it's blocked.). I wonder if `||gorin.jp/tokyo-assets/static/entrance/gorin_tead_prd/$subdocument,redirect=noopframe` helps - I've fixed a similar Vivaldi + uBO issue by such a filter: https://github.com/uBlockOrigin/uAssets/pull/8164
