### ISSUE TITLE
www.spiegel.de: ads displayed with shields on

### ISSUE THREAD

**Issue by loposkin** [brave/adblock-lists#621]
Hi,

As the title says the ads on the main page are displayed with shields on. Ublock Origin blocks these ads, so I wonder why it's not the case with Brave Shields. 

It looks like the ads are added with javascript after site loads completely and they are served from own CDN of the site(maybe I am wrong).

Anyway, I hope you can fix this in the next updates.

**Comment by ryanbr** [comment]
Should be resolved @loposkin , can you confirm?

**Comment by loposkin** [comment]
Hi, yes! It works for a couple of days. Thanks a lot!
