### ISSUE TITLE
Fingerprint blocking adds noise to photopea editor

### ISSUE THREAD

**Issue by ChildishGiant** [brave/adblock-lists#638]
See https://github.com/photopea/photopea/issues/3704

**Comment by pes10k** [comment]
Thank you for the bug report!

Yes, what you're seeing is a side effect of Brave's fingerprint randomization protections (you can read more here https://brave.com/privacy-updates-4).  The effect should be extremely small (a small number of pixels should have their lowest bit flipped, and only on canvas readback) but if you have a fine eye, or you are saving the same image over and over it may be noticeable.

However, what you're showing in that video looks like way more randomization that I'd expect.  Let me check on our side to see if there might be a bug.

In the meantime though, you should be able to solve the issue by going into the shields settings and disabling fingerprinting protections for only this site.

**Comment by pes10k** [comment]
I'm going to move this issue over to where we track bugs in the core of Brave browser, since this isn't directly an adblock-list issue.  That new issue is at https://github.com/brave/brave-browser/issues/17850
