### ISSUE TITLE
vg.no

### ISSUE THREAD

**Issue by DandelionSprout** [brave/adblock-lists#768]
I received an E-mail from their publishing team where they complained that `Annonsørinnhold` ("Advertiser content") banners on the frontpage were blocked in Brave, whereas the content articles were not due to Brave's inability to block DOM elements; which caused problems with their ad disclosure policies.

As such, and because:
* I promised them to fix it *somehow* before tomorrow CET,
* I'm not currently aware of any such things as `!#if !env_brave` I could use in situations like these,
* Dandelion Sprout's Nordic Filters can't add Brave-specific fixes if the fixes break things in uBO/AdGuard/ABP,

I've got little choice but to hope for the fasttrack addition of `@@||akamai.vgc.no/drfront3^$image` to Brave Unbreak.

The content, including the banner that thus will need to be whitelisted (Note that the articles rotate between each page load): 
![image](https://user-images.githubusercontent.com/22780683/153043791-3a069bff-c9e0-45bf-9e9f-6fa2afede5f6.png)

**Comment by ryanbr** [comment]
What filter is causing it @DandelionSprout ?

**Comment by DandelionSprout** [comment]
Dandelion Sprout's Nordic Filters (since its `||akamai.vgc.no/drfront3^$image` entry makes perfect sense in adblockers that support cosmetic filtering).

**Comment by DandelionSprout** [comment]
Okay, so I ended up moving the entry to [an extension file](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFilters-NotBrave.txt), on the semi-qualified guess that Brave doesn't support `!#include`.

I've also been informed elsewhere than on GitHub that the OP problem only affect users who use Standard Mode (which is however the default) instead of Aggressive Mode; and that DOM blocking in Standard Mode has been added to Brave Nightly.

**Comment by ryanbr** [comment]
Safe to close then @DandelionSprout ?

**Comment by DandelionSprout** [comment]
For the time being, yes.
