### ISSUE TITLE
Doordash ads not being blocked 

### ISSUE THREAD

**Issue by leodoi3** [brave/adblock-lists#791]
Tried it on the aggressive setting.

![image](https://user-images.githubusercontent.com/46114199/158041172-2b367e30-176c-4fd3-8656-25299c762dab.png)

**Comment by ryanbr** [comment]
Which page is that from ? @leodoi3    No ads on https://www.doordash.com/food-delivery/queens-ny-restaurants/british/

**Comment by leodoi3** [comment]
This was on https://www.doordash.com/ (assuming you're logged in and on the delivery tab) , then I clicked on a category i.e Healthy. 

![image](https://user-images.githubusercontent.com/46114199/158259574-17bb582e-8a7e-4e09-a475-3ed72ed97248.png)

**Comment by ryanbr** [comment]
Not blockable in Brave, we don't have procedural fitlers like `:has` https://github.com/brave/adblock-rust/issues/145.

Wasn't able to collapse it, but implemented fix to blank it, https://github.com/easylist/easylist/commit/1bc7830b34ab6ac437279493f6f32b6fcc2c369a

@leodoi3
