### ISSUE TITLE
New Youtube Ad Getting Past Ad-block

### ISSUE THREAD

**Issue by ScamCast** [brave/adblock-lists#820]
There seems to be a new Youtube Ad that is getting placed on the Youtube homepage. It only appears sometimes, might take a while of refreshing to replicate if you have already had it displayed. 

```
Elements:
ytd-video-masthead-ad-primary-video-overlay-renderer
ytd-video-masthead-ad-primary-video-renderer
ytd-video-masthead-ad-v3-renderer

Classes
.ytd-video-masthead-ad-primary-video-overlay-renderer
.ytd-video-masthead-ad-primary-video-renderer
.ytd-video-masthead-ad-v3-renderer
```

![image](https://user-images.githubusercontent.com/56202326/162481894-c09d65fc-6d94-4f6a-abc9-0293cc8c9645.png)

**Comment by ryanbr** [comment]
We can safely close this @ScamCast, since we're block the parent ID `masthead-ad` already, which will block the other divs below it.
