### ISSUE TITLE
CleanURL parameter addition request

### ISSUE THREAD

**Issue by snowbound** [brave/adblock-lists#986]
Problem with this [URL](https://apnews.com/article/sports-business-new-zealand-snowboarding-climate-and-environment-52764ef5d762a18ba359da697a53d659?taid=633e49ccdef0cc000141ff12&utm_campaign=TrueAnthem&utm_medium=AP&utm_source=Twitter) The ?taid= is not being stripped off the URL on Version 1.45.95 Chromium: 106.0.5249.103 . The URL loads fine without that parameter and its associated string on the URL.

**Comment by snowbound** [comment]
The TPCC= parameter is not being stripped

https://techcrunch.com/2022/10/18/kanye-joins-the-ranks-of-arrogant-billionaires-buying-their-own-echo-chambers/?tpcc=TechCrunchPlusTwitter

**Comment by pes10k** [comment]
cc @ryanbr @fmarier

**Comment by fmarier** [comment]
Thanks for sending these @snowbound . I've included them in #992.

**Comment by fmarier** [comment]
@ryanbr Neither are on the [AdGuard list](https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_17_TrackParam/filter.txt), but `tpcc` should be pretty safe if it's just scoped to TechCrunch. The other one (`taid`) seems very generic. Do you think it might cause webcompat problems? Should we include it in our list?

**Comment by fmarier** [comment]
After talking to Ryan, I removed `taid` from my PR. It's too risky to remove globally (it might break pages).
