### ISSUE TITLE
derstandard.at anti adblock detection wall (brave on android)

### ISSUE THREAD

**Issue by Esokrates** [brave/adblock-lists#991]
derstandard.at currently works fine on desktop browser with ublock origin etc, where you have to accept the cookie banner and after that you can browse all the articles.
This used to work on mobile as well, however they changed something and now the site always displays the anti adblock wall (Brave on Android):
![photo_2022-10-25_14-31-51](https://user-images.githubusercontent.com/17780185/197773678-01dedcd2-e98a-498d-b2cf-7d7222a37144.jpg)

Would be great if you could unbreak the site. On a side node: when using dns.adguard.com as secure dns in Android the page is broken as well, which also was not the case a few weeks ago.

**Comment by Esokrates** [comment]
Toggling the "Block scripts" toogle makes the wall go away and it is possible to read some articles, however many elements do not load, so the site is only partially useable this way.

**Comment by Esokrates** [comment]
Today is started to work in Brave on Android :-), so either this is a coincidence (which seems unlikely given that chome with dns filtering is still blocked) or someone saw this issue and pushed a fix somewhere? If the latter is the case, I would be happy if you could link the change in here.

**Comment by Esokrates** [comment]
As of now regular articles on the site work great, live articles (https://www.derstandard.at/live) however fail to load:

Example: https://www.derstandard.at/jetzt/livebericht/2000140238872/usa-widersprechen-russischer-behauptung-von-schmutziger-bombe

![photo_2022-10-26_15-03-45](https://user-images.githubusercontent.com/17780185/198033034-d9495b27-2ea4-4b9a-bfde-34233623a642.jpg)

Applies to both regular and aggressive blocking.

**Comment by Esokrates** [comment]
Seems the reason it started working was due to the fix pushed here: https://github.com/uBlockOrigin/uAssets/issues/15404
However, there remains the problem with live articles not loading.

**Comment by ryanbr** [comment]
Closing, should be fixed in uBO here. The same rules are used in Brave
